### ISSUE TITLE
Getting msgs in chat when hovering over items

### ISSUE THREAD

**Issue by Nillx** [CKNOEP/RatingBuster#11]
Im seeing this msg in chat when im hovering over my equipped items (warlock)
![image](https://user-images.githubusercontent.com/34476875/190919809-c5cc9521-a247-4f65-ab5f-d557d94338d0.png)

**Comment by CKNOEP** [comment]
oups, i fix it sorry

**Comment by Nillx** [comment]
Now im seeing this numbers 
![image](https://user-images.githubusercontent.com/34476875/191117768-fa3b9039-1214-41de-8210-920e70d2c215.png)
