### ISSUE TITLE
stat breakdown in chat window

### ISSUE THREAD

**Issue by omegarosu** [CKNOEP/RatingBuster#12]
Shows in the chat window the stat breakdown of str into attack power when i hover mouse over items(also triggers when pressing ctri,alt or shift over that item)
![image](https://user-images.githubusercontent.com/113864988/190932682-2c2331f7-2b58-46aa-8bb8-6bf3f39217ea.png)

**Comment by CKNOEP** [comment]
I use the fonction print () to debug , my bad
