### ISSUE TITLE
Spirit for Warlocks (Fel Armor)

### ISSUE THREAD

**Issue by nistra123** [CKNOEP/RatingBuster#13]
Hey, i would like suggest something!

![image](https://user-images.githubusercontent.com/84995187/191962187-92cae297-3158-444e-a563-16d394f2a10a.png)

Get a statsummary for Spirit aswell, Warlocks for example gain spellpower from Spirit and it is calculated with your RB version but its not showing behind Spirit as of now maybe you can change that, ty :)

**Comment by CKNOEP** [comment]
Fix in version of the Day
