### ISSUE TITLE
Settings don't save

### ISSUE THREAD

**Issue by Vishiswaz** [CKNOEP/RatingBuster#2]
I've changed my settings for this addon 3 times now, only to have the settings be reset to defaults on relog. It's extremely annoying. None of my other addons are having this issue.

Settings I change:

- Stat Breakdown > Stamina > Show Health toggled on
- Stat Breakdown > Intellect > Show Healing, Spell Crit, Spell Damage toggled off
- Stat Summary > Stat - Basic > Sum Combat Mana Regen, Mastery (in Classic??? wtf?) toggled off
- Stat Summary > Stat - Physical > Sum Attack Power, Crit Chance, Haste toggled off
- Stat Summary > Stat - Spell > Sum Spell Haste, Sum Spell Crit Chance toggled off
- Stat Summary > Stat - Tank > Sum Armor, Avoidance toggled on
- Stat Summary > Stat - Tank > Sum Resilience toggled off

**Comment by Vishiswaz** [comment]
I checked, there appears to be no settings file in my WTF\Account\accountnamehere\realm\character\SavedVariables

There is one in Account/SavedVariables but all it has in it is "RatingBusterDB = nil"

**Comment by CKNOEP** [comment]
Fixed: Profiles should now work in the last version
