### ISSUE TITLE
add sockets gems for all specs

### ISSUE THREAD

**Issue by CryptoLogiq** [CKNOEP/RatingBuster#24]
it's possible to add a socket for all spec and compare for current spec or switch for spec 1 or 2 ?

**Comment by CKNOEP** [comment]
Hi;
I have to finish the work on the presets. everything is in place, there are still a few lines of code to write. I will probably next week

**Comment by CKNOEP** [comment]
PS : Je cause la France , l'ami

**Comment by CKNOEP** [comment]
Comme illustré ci dessous:

- Active dans le menu déroulant  Gemmes prédéfinies 2
- renseigne les gemmes voulues (Avec 1 ID d'item , ex 
- Tu auras ton switch de comparaison si tu maintien la touche Raccourci clavier définie.

https://cdn.discordapp.com/attachments/1068249336602964070/1073708499445489824/image.png

**Comment by CryptoLogiq** [comment]
Wohw !

Great job and faster reply !

You are strong man ^^

**Comment by CryptoLogiq** [comment]
Merci beaucoup ;)
