### ISSUE TITLE
Comparing items, ratings not showing.

### ISSUE THREAD

**Issue by Nillx** [CKNOEP/RatingBuster#6]
Thanks for the updates. Is it possible to show the stats on the currently equipped item as well?

![Screenshot 2022-09-05 224250](https://user-images.githubusercontent.com/34476875/188509497-bf6b11fe-83bb-4cbd-b2ab-7272db6cfeb2.jpg)

**Comment by CKNOEP** [comment]
Hi, I don't understand the point of comparing an item to itself

**Comment by Nillx** [comment]
I meant i wish it was displaying the rating stats on the item to the right as well (my currently equipped item). You can see on the screenshot that its not showing them. Makes it a bit easier to compare.

**Comment by Nillx** [comment]
This also extends to items previewed from addons like atlas loot. It doesnt show the %s
![image](https://user-images.githubusercontent.com/34476875/189240058-1923e642-c893-44d5-9c21-780c9f4cded0.png)

**Comment by CKNOEP** [comment]
Fix in last release  today
